export interface GalleryImageConfig {
  id: string
  src: string
  title: string
  description: string
  category: "training" | "vehicles" | "facilities" | "events" | "team"
  location?: string
  featured?: boolean
  likes?: number
  views?: number
  date?: string
  tags?: string[]
}

// PIXIESET GALLERY: https://ian51.pixieset.com/fivestardrivingschoolshoot/
// Instructions for adding images:
// 1. Download images from PIXIESet gallery
// 2. Place them in /public/images/gallery/{category}/
// 3. Add entry below with the image path
// 4. Update metadata as needed

export const GALLERY_IMAGES: GalleryImageConfig[] = [
  // NEW PROFESSIONAL VEHICLE PHOTOS
  {
    id: "vehicles-fleet-stadium",
    src: "/images/mg-01w22.jpg",
    title: "Fleet Lineup at Stadium",
    description: "Three training vehicles showcased at the stadium - Toyota Fielder, Corolla Axio, and Mazda 3",
    category: "vehicles",
    location: "Kasarani Stadium",
    featured: true,
    likes: 312,
    views: 2456,
    date: "2024-02-15",
    tags: ["fleet", "vehicles", "stadium", "showcase", "branded"],
  },
  {
    id: "vehicles-fleet-lineup",
    src: "/images/mg-0050.jpeg",
    title: "Training Fleet Ready",
    description: "Well-maintained Toyota Fielder training vehicles lined up and ready for student lessons",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 289,
    views: 2234,
    date: "2024-02-15",
    tags: ["fleet", "toyota", "fielder", "lineup", "training"],
  },
  {
    id: "vehicles-mazda-front",
    src: "/images/mg-013gfv7.jpg",
    title: "Mazda 3 Training Vehicle",
    description: "Modern white Mazda 3 with doors open showcasing Five Star Driving School branding",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 267,
    views: 2089,
    date: "2024-02-15",
    tags: ["mazda", "mazda3", "branded", "modern", "training"],
  },
  {
    id: "vehicles-fielder-white",
    src: "/images/mg-0039.jpeg",
    title: "White Toyota Fielder",
    description: "Beautiful white Toyota Fielder wagon with full Five Star branding on scenic backdrop",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 245,
    views: 1945,
    date: "2024-02-15",
    tags: ["toyota", "fielder", "white", "wagon", "branded"],
  },
  {
    id: "vehicles-corolla-silver",
    src: "/images/mg-00e17.jpg",
    title: "Silver Toyota Corolla Axio",
    description: "Sleek silver Toyota Corolla Axio training vehicle with professional Five Star livery",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 234,
    views: 1856,
    date: "2024-02-15",
    tags: ["toyota", "corolla", "axio", "silver", "sedan"],
  },
  {
    id: "vehicles-fielder-side",
    src: "/images/mg-0041.jpeg",
    title: "Toyota Fielder Side Profile",
    description: "White Toyota Fielder wagon showcasing the complete Five Star branding design",
    category: "vehicles",
    location: "Training Ground",
    featured: false,
    likes: 198,
    views: 1567,
    date: "2024-02-15",
    tags: ["toyota", "fielder", "side-profile", "branding"],
  },
  {
    id: "vehicles-corolla-rear",
    src: "/images/mg-0028.jpeg",
    title: "Toyota Corolla Axio Rear View",
    description: "Silver Toyota Corolla Axio showing rear three-quarter angle with safety messaging",
    category: "vehicles",
    location: "Training Ground",
    featured: false,
    likes: 187,
    views: 1423,
    date: "2024-02-15",
    tags: ["toyota", "corolla", "rear", "safety", "caution"],
  },
  {
    id: "vehicles-mazda-portrait",
    src: "/images/mg-0007.jpeg",
    title: "Mazda 3 Portrait Shot",
    description: "Stunning portrait angle of the white Mazda 3 training vehicle against blue sky",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 256,
    views: 1978,
    date: "2024-02-15",
    tags: ["mazda", "portrait", "sky", "professional"],
  },
  {
    id: "vehicles-mazda-dynamic",
    src: "/images/mg-0005.jpeg",
    title: "Mazda 3 Dynamic Angle",
    description: "White Mazda 3 captured from a dynamic low angle showcasing its modern design",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 267,
    views: 2045,
    date: "2024-02-15",
    tags: ["mazda", "dynamic", "angle", "modern", "design"],
  },

  {
    id: "vehicles-logo-closeup",
    src: "/images/mg-0054.jpeg",
    title: "Five Star Branding Close-Up",
    description:
      "Detailed close-up of Five Star Driving School logo and branding on vehicle door with fleet in background",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 278,
    views: 2134,
    date: "2024-02-15",
    tags: ["branding", "logo", "close-up", "detail", "professional"],
  },
  {
    id: "vehicles-fielder-rear-full",
    src: "/images/mg-0052.jpeg",
    title: "Toyota Fielder Rear View",
    description: "Full rear view of Toyota Fielder showing complete safety signage, L plates, and caution messaging",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 245,
    views: 1923,
    date: "2024-02-15",
    tags: ["toyota", "fielder", "rear", "safety", "L-plates", "caution"],
  },
  {
    id: "vehicles-fleet-rear-lineup",
    src: "/images/mg-0080.jpeg",
    title: "Fleet Rear View Lineup",
    description: "Multiple training vehicles lined up showing rear signage with roof-mounted school signs",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 256,
    views: 2012,
    date: "2024-02-15",
    tags: ["fleet", "lineup", "rear", "signage", "roof-signs"],
  },
  {
    id: "vehicles-three-car-side",
    src: "/images/mg-0074.jpeg",
    title: "Three Training Vehicles Side View",
    description: "Three-car formation showing silver Corolla Axio and white Toyota Fielders with full branding",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 267,
    views: 2089,
    date: "2024-02-15",
    tags: ["fleet", "formation", "toyota", "fielder", "corolla"],
  },
  {
    id: "vehicles-mazda-door-portrait",
    src: "/images/mg-0055.jpeg",
    title: "Mazda Door Branding Portrait",
    description: "Portrait close-up of Mazda 3 door featuring Five Star logo with fleet vehicle in background",
    category: "vehicles",
    location: "Training Ground",
    featured: false,
    likes: 198,
    views: 1567,
    date: "2024-02-15",
    tags: ["mazda", "portrait", "branding", "door", "detail"],
  },
  {
    id: "vehicles-artistic-roof-sign",
    src: "/images/mg-0053.jpeg",
    title: "Artistic Roof Sign Shot",
    description: "Creative angle capturing Five Star roof sign through vehicle elements against cloudy sky",
    category: "vehicles",
    location: "Training Ground",
    featured: false,
    likes: 187,
    views: 1423,
    date: "2024-02-15",
    tags: ["artistic", "roof-sign", "creative", "sky", "angle"],
  },
  {
    id: "vehicles-three-car-portrait",
    src: "/images/mg-0079.jpeg",
    title: "Three Vehicles Portrait Formation",
    description: "Portrait orientation showing three training vehicles with prominent star branding and roof signs",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 234,
    views: 1845,
    date: "2024-02-15",
    tags: ["fleet", "portrait", "formation", "branding", "stars"],
  },
  {
    id: "vehicles-suv-crossover-lineup",
    src: "/images/mg-0087.jpeg",
    title: "SUV & Crossover Fleet",
    description: "Three SUV/crossover training vehicles including Mazda CX with fleet numbers and full branding",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 289,
    views: 2234,
    date: "2024-02-15",
    tags: ["suv", "crossover", "mazda-cx", "fleet-numbers", "lineup"],
  },
  {
    id: "vehicles-three-car-front-angle",
    src: "/images/mg-0068.jpeg",
    title: "Three-Car Front Angle Showcase",
    description: "Professional front-angle shot of Mazda 3, Corolla Axio, and Toyota Fielder training vehicles",
    category: "vehicles",
    location: "Training Ground",
    featured: true,
    likes: 278,
    views: 2156,
    date: "2024-02-15",
    tags: ["mazda", "corolla", "fielder", "front", "showcase", "professional"],
  },

  // TRAINING - ENGINE DEMONSTRATIONS & PRACTICAL SESSIONS
  {
    id: "training-engine-demo-1",
    src: "/images/dji-0262.jpeg",
    title: "Engine Mechanics Training",
    description: "Students and instructors gathered for practical engine compartment explanation and demonstration",
    category: "training",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 212,
    views: 1634,
    date: "2024-01-25",
    tags: ["training", "engine", "practical", "mechanics", "hands-on"],
  },
  {
    id: "training-engine-demo-2",
    src: "/images/dji-0264.jpeg",
    title: "Hands-On Engine Training",
    description: "Instructors teaching vehicle maintenance and engine operation to attentive students",
    category: "training",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 189,
    views: 1456,
    date: "2024-01-25",
    tags: ["training", "hands-on", "engine", "practical", "education"],
  },
  {
    id: "training-session-interactive",
    src: "/images/dji-0263.jpeg",
    title: "Interactive Training Session",
    description: "Group training session with students learning from experienced Five Star instructors",
    category: "training",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 198,
    views: 1512,
    date: "2024-01-25",
    tags: ["training", "group", "interactive", "hands-on", "learning"],
  },
  {
    id: "training-comprehensive-facility",
    src: "/images/dji-0261.jpeg",
    title: "Complete Training Facility",
    description: "Aerial overview of the entire training ground with fleet and demonstration in progress",
    category: "training",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 223,
    views: 1723,
    date: "2024-01-25",
    tags: ["training", "facility", "aerial", "comprehensive", "fleet"],
  },
  {
    id: "training-engine-inspection-1",
    src: "/images/img-2015.jpg",
    title: "Engine Compartment Inspection Training",
    description:
      "Instructors and trainees learning to inspect and understand vehicle engine systems during hands-on training session",
    category: "training",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 167,
    views: 1289,
    date: "2024-01-25",
    tags: ["training", "engine", "inspection", "practical", "maintenance"],
  },
  {
    id: "training-engine-inspection-2",
    src: "/images/img-2017.jpg",
    title: "Detailed Engine Checklist Training",
    description:
      "Trainer conducting comprehensive vehicle inspection checklist training with actual vehicle engine bay",
    category: "training",
    location: "Roysambu Main Facility",
    featured: false,
    likes: 134,
    views: 1045,
    date: "2024-01-25",
    tags: ["training", "inspection", "checklist", "maintenance", "practical"],
  },
  {
    id: "training-crash-demo",
    src: "/images/img-1998.jpg",
    title: "Crash Demonstration & Safety Training",
    description:
      "Students gathered around a crash demonstration vehicle learning about vehicle safety and impact zones",
    category: "training",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 156,
    views: 1234,
    date: "2024-01-25",
    tags: ["training", "safety", "crash-demo", "education", "awareness"],
  },
  {
    id: "training-driving-course",
    src: "/images/img-2161.jpg",
    title: "Simulated Driving Course Training",
    description:
      "Interactive driving course mat with toy vehicles demonstrating road layouts and traffic patterns for theory students",
    category: "training",
    location: "Roysambu Main Facility",
    featured: false,
    likes: 98,
    views: 812,
    date: "2024-01-25",
    tags: ["training", "driving-course", "interactive", "theory", "simulation"],
  },

  // VEHICLES - FLEET SHOWCASE
  {
    id: "vehicles-fleet-aerial-1",
    src: "/images/dji-0268.jpeg",
    title: "Complete Training Fleet Overview",
    description: "Aerial view of our entire Five Star Driving School fleet with 50+ well-maintained training vehicles",
    category: "vehicles",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 245,
    views: 1856,
    date: "2024-01-25",
    tags: ["fleet", "vehicles", "aerial", "training", "modern"],
  },
  {
    id: "vehicles-fleet-aerial-2",
    src: "/images/dji-0267.jpeg",
    title: "Fleet Organization & Layout",
    description: "Perfect demonstration of our organized vehicle storage and maintenance facility",
    category: "vehicles",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 198,
    views: 1543,
    date: "2024-01-25",
    tags: ["fleet", "organization", "facility", "vehicles", "training"],
  },
  {
    id: "vehicles-trio-top-down-1",
    src: "/images/dji-0258.jpeg",
    title: "Three Training Vehicles - Color Variety",
    description: "Showcase of our diverse vehicle fleet with manual transmission, automatic, and red training vehicles",
    category: "vehicles",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 167,
    views: 1289,
    date: "2024-01-25",
    tags: ["vehicles", "fleet", "training", "manual", "automatic"],
  },
  {
    id: "vehicles-trio-top-down-2",
    src: "/images/dji-0257.jpeg",
    title: "Three Branded Training Vehicles",
    description: "Professional five star branded vehicles showing the range of our training fleet",
    category: "vehicles",
    location: "Roysambu Main Facility",
    featured: false,
    likes: 134,
    views: 1045,
    date: "2024-01-25",
    tags: ["vehicles", "branded", "training", "fleet"],
  },
  {
    id: "vehicles-trio-top-down-3",
    src: "/images/dji-0256.jpeg",
    title: "Vehicle Fleet Collection",
    description: "Beautiful aerial perspective of our diverse training vehicle collection",
    category: "vehicles",
    location: "Roysambu Main Facility",
    featured: false,
    likes: 123,
    views: 956,
    date: "2024-01-25",
    tags: ["vehicles", "fleet", "training", "collection"],
  },
  {
    id: "vehicles-demo-session",
    src: "/images/img-1996.jpg",
    title: "Vehicle Demonstration Session",
    description:
      "Instructor demonstrating vehicle features and mechanics to a group of attentive students in outdoor setting",
    category: "vehicles",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 145,
    views: 1098,
    date: "2024-01-25",
    tags: ["vehicles", "demonstration", "training", "fleet", "education"],
  },

  // FACILITIES - OFFICE & RECEPTION
  {
    id: "facilities-reception-area",
    src: "/images/img-2245.jpg",
    title: "Modern Reception & Customer Service",
    description:
      "Professional staff assisting student at Five Star Driving School reception desk with modern facilities",
    category: "facilities",
    location: "Main Office",
    featured: true,
    likes: 112,
    views: 945,
    date: "2024-01-25",
    tags: ["facilities", "reception", "customer-service", "office", "modern"],
  },
  {
    id: "facilities-office-counter",
    src: "/images/img-2176.jpg",
    title: "Office Counter & Registration",
    description: "Warm and professional office environment with staff assisting customers at the counter",
    category: "facilities",
    location: "Roysambu Branch",
    featured: false,
    likes: 89,
    views: 756,
    date: "2024-01-25",
    tags: ["facilities", "office", "registration", "counter", "service"],
  },

  // EVENTS & BRAND - SIGNAGE & BRANDING
  {
    id: "brand-signage",
    src: "/images/img-2266.jpg",
    title: "Five Star Driving School Signage",
    description: "Official FIVE STAR DRIVING SCHOOL signage displaying brand identity and contact information",
    category: "events",
    location: "Street Front",
    featured: false,
    likes: 76,
    views: 634,
    date: "2024-01-25",
    tags: ["brand", "signage", "identification", "location"],
  },

  // TEAM - GROUP GATHERINGS
  {
    id: "team-group-photo-1",
    src: "/images/img-2083.jpg",
    title: "Team Building & Training Event",
    description: "Full team and students gathering for training event showcase and team building activities",
    category: "team",
    location: "Roysambu Main Facility",
    featured: true,
    likes: 189,
    views: 1467,
    date: "2024-01-25",
    tags: ["team", "group", "event", "training", "community"],
  },
  {
    id: "team-group-photo-2",
    src: "/images/img-2082.jpg",
    title: "Extended Team Group Photo",
    description: "Large group photo of FIVE STAR team members, instructors and participants at main facility",
    category: "team",
    location: "Roysambu Main Facility",
    featured: false,
    likes: 145,
    views: 1123,
    date: "2024-01-25",
    tags: ["team", "group-photo", "family", "instructors", "staff"],
  },
]
